plot_config_inv = {
    "save_plot": False,
    "offset": 0,
    "linewidth": 2.0,
    "fig_width": 12,
    "fig_height": 7,
    "plot_axis_range_x": [1e0, 1e6],
    "plot_axis_range_y": [1e0, 1e11],
    "xticks_fontsize": 12,
    "yticks_fontsize": 12,
    "plot_title": "Radiotoxicity of Spent Fuel",
    "plot_subtitle": "SF at discharge, Th-U233 (4.15%), 44.5 MWd/kgIHM, Adults",
    "plot_xlabel": "Time (years)",
    "plot_ylabel": "Radiotoxicity [Sv/t$_{IHM}$]",
    "show_footnote": True,
    "footnote_text": "IHM = Initial Heavy Metal\nSF = Spent Fuel",
    "font_name": "DejaVu Sans",
    "title_fontsize": 14,
    "label_fontsize": 13,
    "legend_fontsize": 12,
    "subtitle_fontsize": 12,
    "show_legend": True,
    "plot_legend_loc": "upper right",
    "legend_outside": False,
    "plot_grid_show": True,
    "plot_grid_which": "major",
    "plot_grid_linestyle": "--",
    "plot_grid_linewidth": 0.5,
    "dpi": 300,
}