# Graph settings
plot_config = {
    "save_plot": False,
    "offset": 0,
    "linewidth": 2.0,
    "fig_width": 12,
    "fig_height": 7,
    "plot_axis_range_x": [1e0, 1e6],
    "plot_axis_range_y": [1e0, 1e10],
    "xticks_fontsize": 12,
    "yticks_fontsize": 12,
    "plot_title": "Radiotoxicity of Spent Fuel incl. Decay Products",
    "plot_subtitle": "SF at discharge, UO2, 4.5%, 65 GWd/t, n$_{repro. cyc.}$=10, Adults",
    "plot_xlabel": "Time (years)",
    "plot_ylabel": "Radiotoxicity [Sv/t$_{IHM}$]",
    "show_footnote": False,
    "footnote_text": "res = residuals\nPart. eff.s: U = 99.88%, Pu = 99.88%, MA = varied",
    "font_name": "DejaVu Sans",
    "title_fontsize": 14,
    "label_fontsize": 13,
    "legend_fontsize": 10,
    "subtitle_fontsize": 12,
    "show_legend": True,
    "plot_legend_loc": "upper right",
    "legend_outside": False,
    "plot_grid_show": True,
    "plot_grid_which": "major",
    "plot_grid_linestyle": "--",
    "plot_grid_linewidth": 0.5,
    "dpi": 300,
}
